# Generated by Django 4.0.3 on 2022-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder01App', '0006_cursos_descripcion_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_alumno', models.IntegerField()),
                ('nombre_alumno', models.CharField(max_length=20)),
                ('apellido_alumno', models.CharField(max_length=20)),
                ('curso_alumno', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('HTML', 'HTML')], max_length=20)),
                ('calificacion_alumno', models.IntegerField()),
            ],
        ),
    ]
